CREATE TABLE SO_TRAINING_FEATURES (
  Id                            INT      NOT NULL,
  successful                    INT      NOT NULL DEFAULT '1',
  StartDate                     DATETIME NOT NULL,
  AnswerDate                    DATETIME          DEFAULT NULL,
  EndDate                       DATETIME NOT NULL,
  answer_duration               INT               DEFAULT '0',
  answer_was_edited             TINYINT           DEFAULT '0',
  num_code_snippet              INT               DEFAULT '0',
  num_images                    INT               DEFAULT '0',
  code_len                      INT               DEFAULT '0',
  body_len                      INT               DEFAULT '0',
  num_selfref                   INT               DEFAULT '0',
  num_active_verb               INT               DEFAULT '0',
  title_len                     INT               DEFAULT '0',
  end_que_mark                  TINYINT           DEFAULT '0',
  begin_que_word                TINYINT           DEFAULT '0',
  log_body_len                  INT               DEFAULT '0',
  log_code_len                  INT               DEFAULT '0',
  log_code_snippets             INT               DEFAULT '0',
  log_selfref                   INT               DEFAULT '0',
  log_active_verb               INT               DEFAULT '0',
  tag_popularity                DOUBLE            DEFAULT '0',
  tag_specificity               DOUBLE            DEFAULT '0',
  num_pop_tags_25               INT               DEFAULT '0',
  num_pop_tags_50               INT               DEFAULT '0',
  num_pop_tags_100              INT               DEFAULT '0',
  num_subs_ans                  DOUBLE            DEFAULT '0',
  percent_subs_ans              DOUBLE            DEFAULT '0',
  num_subs_t                    DOUBLE            DEFAULT '0',
  percent_subs_t                DOUBLE            DEFAULT '0',
  log_min_tag_subs              INT               DEFAULT '0',
  log_max_tag_subs              INT               DEFAULT '0',
  log_tag_popularity            INT               DEFAULT '0',
  log_tag_specifity             INT               DEFAULT '0',
  log_num_subs_ans              INT               DEFAULT '0',
  log_percent_subs_ans          INT               DEFAULT '0',
  log_num_subs_t                INT               DEFAULT '0',
  log_percent_subs_t            INT               DEFAULT '0',
  bounty_height                 INT               DEFAULT '0',
  num_answers_bounty            INT               DEFAULT '0',
  time_till_bounty_creation     INT               DEFAULT '0',
  log_time_till_bounty_creation DOUBLE            DEFAULT '0',
  question_score                INT               DEFAULT '0',
  view_count                    INT               DEFAULT '0',
  log_avg_daily_views           DOUBLE            DEFAULT '0',
  other_active_bounties         INT               DEFAULT '0',
  log_num_answers               INT               DEFAULT '0',
  log_view_count                INT               DEFAULT '0',
  log_other_bounties            INT               DEFAULT '0',
  num_comments_bounty           INT               DEFAULT '0',
  len_comments_bounty           INT               DEFAULT '0',
  avg_len_comments              DOUBLE            DEFAULT '0',
  log_num_comments              INT               DEFAULT '0',
  log_len_comments              INT               DEFAULT '0',
  body_ari                      DOUBLE            DEFAULT '0',
  body_cli                      DOUBLE            DEFAULT '0',
  body_fre                      DOUBLE            DEFAULT '0',
  body_gfi                      DOUBLE            DEFAULT '0',
  body_avg_chars                INT               DEFAULT '0',
  body_avg_words                INT               DEFAULT '0',
  log_body_ari                  INT               DEFAULT '0',
  log_body_cli                  INT               DEFAULT '0',
  log_body_fre                  INT               DEFAULT '0',
  log_body_gfi                  INT               DEFAULT '0',
  log_avg_words                 INT               DEFAULT '0',
  topics                        blob,
  vp_topics                     blob,
  PRIMARY KEY (Id)
);

CREATE INDEX training_feature_1 ON SO_TRAINING_FEATURES (successful);
CREATE INDEX training_feature_2 ON SO_TRAINING_FEATURES (AnswerDate);
CREATE INDEX training_feature_3 ON SO_TRAINING_FEATURES (StartDate);
CREATE INDEX training_feature_4 ON SO_TRAINING_FEATURES (answer_was_edited);