CREATE TABLE `training_features` (
  `Id` int(11) NOT NULL,
  `successful` int(11) NOT NULL DEFAULT '1',
  `StartDate` datetime NOT NULL,
  `AnswerDate` datetime DEFAULT NULL,
  `EndDate` datetime NOT NULL,
  `answer_duration` int(11) DEFAULT '0',
  `answer_was_edited` tinyint(1) DEFAULT '0',
  `num_code_snippet` int(11) DEFAULT '0',
  `num_images` int(11) DEFAULT '0',
  `code_len` int(11) DEFAULT '0',
  `body_len` int(11) DEFAULT '0',
  `num_selfref` int(11) DEFAULT '0',
  `num_active_verb` int(11) DEFAULT '0',
  `title_len` int(11) DEFAULT '0',
  `end_que_mark` tinyint(1) DEFAULT '0',
  `begin_que_word` tinyint(1) DEFAULT '0',
  `log_body_len` int(11) DEFAULT '0',
  `log_code_len` int(11) DEFAULT '0',
  `log_code_snippets` int(11) DEFAULT '0',
  `log_selfref` int(11) DEFAULT '0',
  `log_active_verb` int(11) DEFAULT '0',
  `tag_popularity` double DEFAULT '0',
  `tag_specificity` double DEFAULT '0',
  `num_pop_tags_25` int(11) DEFAULT '0',
  `num_pop_tags_50` int(11) DEFAULT '0',
  `num_pop_tags_100` int(11) DEFAULT '0',
  `num_subs_ans` double DEFAULT '0',
  `percent_subs_ans` double DEFAULT '0',
  `num_subs_t` double DEFAULT '0',
  `percent_subs_t` double DEFAULT '0',
  `log_min_tag_subs` int(11) DEFAULT '0',
  `log_max_tag_subs` int(11) DEFAULT '0',
  `log_tag_popularity` int(11) DEFAULT '0',
  `log_tag_specifity` int(11) DEFAULT '0',
  `log_num_subs_ans` int(11) DEFAULT '0',
  `log_percent_subs_ans` int(11) DEFAULT '0',
  `log_num_subs_t` int(11) DEFAULT '0',
  `log_percent_subs_t` int(11) DEFAULT '0',
  `bounty_height` int(11) DEFAULT '0',
  `num_answers_bounty` int(11) DEFAULT '0',
  `time_till_bounty_creation` int(11) DEFAULT '0',
  `log_time_till_bounty_creation` double DEFAULT '0',
  `question_score` int(11) DEFAULT '0',
  `view_count` int(11) DEFAULT '0',
  `log_avg_daily_views` double DEFAULT '0',
  `other_active_bounties` int(11) DEFAULT '0',
  `log_num_answers` int(11) DEFAULT '0',
  `log_view_count` int(11) DEFAULT '0',
  `log_other_bounties` int(11) DEFAULT '0',
  `num_comments_bounty` int(11) DEFAULT '0',
  `len_comments_bounty` int(11) DEFAULT '0',
  `avg_len_comments` double DEFAULT '0',
  `log_num_comments` int(11) DEFAULT '0',
  `log_len_comments` int(11) DEFAULT '0',
  `body_ari` double DEFAULT '0',
  `body_cli` double DEFAULT '0',
  `body_fre` double DEFAULT '0',
  `body_gfi` double DEFAULT '0',
  `body_avg_chars` int(11) DEFAULT '0',
  `body_avg_words` int(11) DEFAULT '0',
  `log_body_ari` int(11) DEFAULT '0',
  `log_body_cli` int(11) DEFAULT '0',
  `log_body_fre` int(11) DEFAULT '0',
  `log_body_gfi` int(11) DEFAULT '0',
  `log_avg_words` int(11) DEFAULT '0',
  `topics` blob,
  `vp_topics` blob,
  PRIMARY KEY (`Id`),
  KEY `successful` (`successful`),
  KEY `AnswerDate` (`AnswerDate`),
  KEY `StartDate` (`StartDate`),
  KEY `answer_was_edited` (`answer_was_edited`)
);